[package]
name = "rougelike-quicksilver"
version = "0.1.0"
authors = ["Chapman Siu <chapm0n.siu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5" # make sure this is the latest version

